# Generated by Django 5.1.2 on 2025-03-30 17:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cow_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
