# Generated by Django 5.1.2 on 2025-05-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cow_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='feeding_scheme',
            field=models.CharField(choices=[('PASTURE', 'Pasture Grazing'), ('SUPPLEMENTED_PASTURE', 'Pasture + Supplement'), ('FEEDLOT', 'Feedlot Intensive'), ('MIXED', 'Mixed Diet'), ('OTHER', 'Other')], default='PASTURE', help_text='The feeding regimen for this cow.', max_length=100),
        ),
    ]
